apiVersion: "nais.io/v1"
kind: "Alert"
metadata:
  name: oh-alerts
  namespace: oppgavehandtering
  labels:
    team: oppgavehandtering
spec:
  receivers:
    slack:
      channel: '#oh-alerts'
      prependText:  '<!here> | '
      send_resolved: true
      icon_emoji: ':gcp:'
  route:
    repeat_interval: 3h
  alerts:
    - alert: errorRate
      expr: (100 * sum by (log_app) (rate(logd_messages_total{log_team="oppgavehandtering",log_level="Error"}[5m])) / sum by (log_app) (rate(logd_messages_total{log_team="oppgavehandtering"}[5m]))) > 10
      for: 2m
      description: "Høy feilrate: {{  $value | printf \"%.1f\" }} % i {{ $labels.log_app }} "
      action: "Sjekk logger"
      severity: danger
    - alert: appDown
      expr: sum(kube_deployment_status_replicas_available{namespace="oppgavehandtering"}) by (deployment) == 0
      for: 2m
      description: "{{ $labels.app }} er nede"
      action: "Sjekk logger"
      severity: danger
    - alert: Økende Consumer Lag - statistikk-behandling
      expr: sum(delta(kafka_consumergroup_group_topic_sum_lag{group="oh-statistikk-behandler-v2" }[10m])) by(group, topic)/(10*60) >1
      for: 10m
      description: "consumer group *{{ $labels.group }}* øker med  {{ $value }} pr sekund på *{{ $labels.topic }}*"
      action: "Sjekk logger"
      severity: danger

